#!/usr/bin/env python3
"""
Environment Setup Script for Instagram Bot
This script helps you create a .env file with the required environment variables.
"""

import os
import getpass

def create_env_file():
    """Create a .env file with user input"""
    
    print("🔧 Instagram Bot Environment Setup")
    print("=" * 40)
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").lower()
        if overwrite != 'y':
            print("❌ Setup cancelled.")
            return
    
    print("📋 Please provide your Instagram API credentials:")
    print()
    
    # Get Instagram Access Token
    print("1. INSTAGRAM_ACCESS_TOKEN")
    print("   Get this from Facebook Developer Console > Your App > Instagram > Generate Token")
    access_token = getpass.getpass("   Enter your Instagram Access Token: ").strip()
    
    if not access_token:
        print("❌ Access token is required!")
        return
    
    # Get App Secret
    print()
    print("2. INSTAGRAM_APP_SECRET")
    print("   Get this from Facebook Developer Console > Your App > Settings > Basic > App Secret")
    app_secret = getpass.getpass("   Enter your Facebook App Secret: ").strip()
    
    if not app_secret:
        print("❌ App secret is required!")
        return
    
    # Get Business Account ID (with default)
    print()
    print("3. INSTAGRAM_BUSINESS_ACCOUNT_ID")
    print("   This is your Instagram Business Account ID")
    business_id = input("   Enter your Business Account ID (default: 17841473964575374): ").strip()
    
    if not business_id:
        business_id = "17841473964575374"
        print("   Using default: 17841473964575374")
    
    # Get Webhook Verify Token (with default)
    print()
    print("4. WEBHOOK_VERIFY_TOKEN")
    print("   This is used for webhook verification")
    verify_token = input("   Enter webhook verify token (default: summy_webhook_verify_token_2025): ").strip()
    
    if not verify_token:
        verify_token = "summy_webhook_verify_token_2025"
        print("   Using default: summy_webhook_verify_token_2025")
    
    # Create .env file
    env_content = f"""# Instagram Bot Environment Variables
# Generated by setup_env.py

# Instagram Messaging API Access Token
INSTAGRAM_ACCESS_TOKEN={access_token}

# Facebook App Secret
INSTAGRAM_APP_SECRET={app_secret}

# Instagram Business Account ID
INSTAGRAM_BUSINESS_ACCOUNT_ID={business_id}

# Webhook Verification Token
WEBHOOK_VERIFY_TOKEN={verify_token}

# Flask Secret Key (auto-generated)
FLASK_SECRET_KEY=your-secret-key-here
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print()
        print("✅ .env file created successfully!")
        print()
        print("📋 Next steps:")
        print("1. Test locally: python3 instagram_message_listener.py")
        print("2. Deploy to Heroku: git push heroku main")
        print("3. Set environment variables on Heroku dashboard")
        print()
        print("🔗 Useful URLs:")
        print("- Local test: http://localhost:5000/")
        print("- API test: http://localhost:5000/api/messages")
        print("- Test message: http://localhost:5000/test-message")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

if __name__ == "__main__":
    create_env_file() 